/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { currentIntakeNum, currentExhaustNum } = props;
  console.log(currentIntakeNum);
  const { nodes, materials } = useGLTF("/House.gltf");
  return (
    <group
      ref={group}
      scale={0.003}
      position={[1, -2, 0]}
      {...props}
      dispose={null}
    >
      <group position={[-679.46, 679.08, 329.98]}>
        {currentIntakeNum === 2 && (
          <group
            position={[679.46, -679.08, -329.98]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes["2_Aluminum_UnderEave_Vent_2"].geometry}
              material={nodes["2_Aluminum_UnderEave_Vent_2"].material}
            />
          </group>
        )}
        {currentIntakeNum === 3 && (
          <group
            position={[679.46, -679.08, -329.98]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes["3_Continuos_UnderEave_Vent_1_2"].geometry}
              material={nodes["3_Continuos_UnderEave_Vent_1_2"].material}
            />
          </group>
        )}
        {currentIntakeNum === 4 && (
          <group
            position={[679.46, -679.08, -329.98]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes["4_Plastic_Soffit_Vent_2"].geometry}
              material={nodes["4_Plastic_Soffit_Vent_2"].material}
            />
          </group>
        )}
        {currentIntakeNum === 5 && (
          <group position={[348.51, 28.82, 94.58]}>
            <mesh
              geometry={nodes["5__Rooftop_Intake-Roof"].geometry}
              material={nodes["5__Rooftop_Intake-Roof"].material}
            />
            <mesh
              geometry={nodes["5__Rooftop_Intake-Roof_1"].geometry}
              material={nodes["5__Rooftop_Intake-Roof_1"].material}
            />
          </group>
        )}

        {currentIntakeNum === 6 && (
          <group
            position={[679.46, -679.08, -329.98]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          >
            <mesh
              geometry={nodes["6_closeable_soffit_vent_2"].geometry}
              material={nodes["6_closeable_soffit_vent_2"].material}
            />
          </group>
        )}
        {currentIntakeNum === 1 && (
          <mesh
            geometry={nodes["1_Gable_Vent"].geometry}
            material={nodes["1_Gable_Vent"].material}
            position={[-198.91, 65.27, -285.22]}
            rotation={[0, -1.57, 0]}
          />
        )}
      </group>
      <group position={[-569.79, 793.72, 129.82]}>
        {currentExhaustNum === 1 && (
          <group position={[569.79, -793.72, -129.82]}>
            <mesh
              geometry={nodes["1_Ridge_Vent_Rigid-Roof1"].geometry}
              material={materials["Roof.1"]}
            />
            <mesh
              geometry={nodes["1_Ridge_Vent_Rigid-Roof"].geometry}
              material={nodes["1_Ridge_Vent_Rigid-Roof"].material}
            />
            <mesh
              geometry={nodes["1_Ridge_Vent_Rigid-House_Main"].geometry}
              material={nodes["1_Ridge_Vent_Rigid-House_Main"].material}
            />
          </group>
        )}
        {currentExhaustNum === 7 && (
          <group position={[246.01, 104.37, -195.4]}>
            <mesh
              geometry={nodes["7_Powered_Exhaust-Roof"].geometry}
              material={nodes["7_Powered_Exhaust-Roof"].material}
            />
            <mesh
              geometry={nodes["7_Powered_Exhaust-House_Main"].geometry}
              material={nodes["7_Powered_Exhaust-House_Main"].material}
            />
          </group>
        )}

        {currentExhaustNum === 2 && (
          <>
            <mesh
              geometry={nodes["2_Ridge_Vent_Mesh"].geometry}
              material={nodes["2_Ridge_Vent_Mesh"].material}
              position={[569.79, -793.72, -129.82]}
            />
            <mesh
              geometry={nodes["2_Ridge_Vent_Shingle_1"].geometry}
              material={nodes["2_Ridge_Vent_Shingle_1"].material}
              position={[569.79, -793.72, -129.82]}
            />
          </>
        )}
        {currentExhaustNum === 3 && (
          <mesh
            geometry={nodes["3_Slantback_Roof_Louvers"].geometry}
            material={nodes["3_Slantback_Roof_Louvers"].material}
            position={[569.79, -793.72, -129.82]}
          />
        )}
        {currentExhaustNum === 4 && (
          <mesh
            geometry={nodes["4__Aluminum_Square_Roof_Louver"].geometry}
            material={nodes["4__Aluminum_Square_Roof_Louver"].material}
            position={[569.79, 73.84, -167.96]}
            rotation={[2.56, 0, 0]}
          />
        )}
        {currentExhaustNum === 5 && (
          <mesh
            geometry={nodes["5_Whirlybirds"].geometry}
            material={nodes["5_Whirlybirds"].material}
            position={[13.26, 104.37, -195.4]}
          />
        )}

        {currentExhaustNum === 6 && (
          <mesh
            geometry={nodes["6_Gable_Vent"].geometry}
            material={nodes["6_Gable_Vent"].material}
            position={[800.27, -26.93, -85.07]}
            rotation={[0, 1.57, 0]}
          />
        )}
      </group>
      <group position={[31.67, 81.2, 196.26]}>
        <group
          position={[-31.67, -81.2, -196.26]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Roof_2-Roof"].geometry}
            material={nodes["Roof_2-Roof"].material}
          />
          <mesh
            geometry={nodes["Roof_2-House_Main"].geometry}
            material={nodes["Roof_2-House_Main"].material}
          />
        </group>
        <group
          position={[-31.67, -81.2, -196.26]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main"].geometry}
            material={nodes["Attic_Cutout_2-House_Main"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window"].geometry}
            material={nodes["Attic_Cutout_2-window"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_1"].geometry}
            material={nodes["Attic_Cutout_2-window_1"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main_1"].geometry}
            material={nodes["Attic_Cutout_2-House_Main_1"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_2"].geometry}
            material={nodes["Attic_Cutout_2-window_2"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_3"].geometry}
            material={nodes["Attic_Cutout_2-window_3"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main_2"].geometry}
            material={nodes["Attic_Cutout_2-House_Main_2"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_4"].geometry}
            material={nodes["Attic_Cutout_2-window_4"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main_3"].geometry}
            material={nodes["Attic_Cutout_2-House_Main_3"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-Siding"].geometry}
            material={nodes["Attic_Cutout_2-Siding"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-Siding_1"].geometry}
            material={nodes["Attic_Cutout_2-Siding_1"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-Siding_2"].geometry}
            material={nodes["Attic_Cutout_2-Siding_2"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_5"].geometry}
            material={nodes["Attic_Cutout_2-window_5"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main_4"].geometry}
            material={nodes["Attic_Cutout_2-House_Main_4"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_6"].geometry}
            material={nodes["Attic_Cutout_2-window_6"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-window_7"].geometry}
            material={nodes["Attic_Cutout_2-window_7"].material}
          />
          <mesh
            geometry={nodes["Attic_Cutout_2-House_Main_5"].geometry}
            material={nodes["Attic_Cutout_2-House_Main_5"].material}
          />
        </group>
        <group position={[-31.67, -81.2, -196.26]}>
          <group position={[0, 0, 2.63]}>
            <mesh
              geometry={nodes.Details_1.geometry}
              material={nodes.Details_1.material}
              position={[0, 0, -2.63]}
            />
            <mesh
              geometry={nodes.Details_2.geometry}
              material={nodes.Details_2.material}
              position={[0, 0, -2.63]}
            />
            <mesh
              geometry={nodes.Details_4.geometry}
              material={nodes.Details_4.material}
              position={[0, 0, -2.63]}
            />
            <mesh
              geometry={nodes.Details_3.geometry}
              material={nodes.Details_3.material}
              position={[0, 0, 7.89]}
            />
          </group>
          <group
            position={[-547.98, 219.45, 153.19]}
            rotation={[Math.PI, 0, -Math.PI]}
          >
            <group position={[-6.1, 63.1, -55.29]}>
              <mesh
                geometry={nodes.Cylinder_1.geometry}
                material={nodes.Cylinder_1.material}
                position={[0.05, -18.15, 0]}
              />
              <mesh
                geometry={nodes.Sphere.geometry}
                material={nodes.Sphere.material}
                position={[-0.1, -27.59, 0]}
              />
              <mesh
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
                position={[0.05, 28.3, 0]}
              />
            </group>
            <group position={[-6.1, 63.1, 65.92]}>
              <mesh
                geometry={nodes.Cylinder_1_2.geometry}
                material={nodes.Cylinder_1_2.material}
                position={[0.05, -18.15, 0]}
              />
              <mesh
                geometry={nodes.Sphere_2.geometry}
                material={nodes.Sphere_2.material}
                position={[-0.1, -27.59, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_2.geometry}
                material={nodes.Cylinder_2.material}
                position={[0.05, 28.3, 0]}
              />
            </group>
            <group position={[12.21, -126.19, -10.62]}>
              <group position={[-47.6, 58.41, 14.7]} rotation={[0, 1.57, 0]}>
                <mesh
                  geometry={nodes.obj1.geometry}
                  material={nodes.obj1.material}
                />
                <mesh
                  geometry={nodes.obj2.geometry}
                  material={nodes.obj2.material}
                />
                <mesh
                  geometry={nodes.obj3.geometry}
                  material={nodes.obj3.material}
                />
                <mesh
                  geometry={nodes.obj4.geometry}
                  material={nodes.obj4.material}
                />
                <mesh
                  geometry={nodes.obj5.geometry}
                  material={nodes.obj5.material}
                />
                <mesh
                  geometry={nodes.obj6.geometry}
                  material={nodes.obj6.material}
                />
                <mesh
                  geometry={nodes.obj7.geometry}
                  material={nodes.obj7.material}
                />
                <mesh
                  geometry={nodes.obj8.geometry}
                  material={nodes.obj8.material}
                />
                <mesh
                  geometry={nodes.obj9.geometry}
                  material={nodes.obj9.material}
                />
              </group>
              <group position={[58.8, -79.05, 14.7]}>
                <mesh
                  geometry={nodes.counters.geometry}
                  material={nodes.counters.material}
                  position={[-73.1, 133.69, 0]}
                />
                <mesh
                  geometry={nodes.sink_1.geometry}
                  material={nodes.sink_1.material}
                  position={[-79.45, 119.48, -0.65]}
                />
              </group>
              <mesh
                geometry={nodes.Bowl_Cylinder.geometry}
                material={nodes.Bowl_Cylinder.material}
                position={[-25.28, 57.01, 91.13]}
              />
              <mesh
                geometry={nodes.Cylinder_5.geometry}
                material={nodes.Cylinder_5.material}
                position={[-23.26, 7.16, 6.24]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Cylinder_4.geometry}
                material={nodes.Cylinder_4.material}
                position={[-14.97, 7.16, -0.3]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_3.geometry}
                material={nodes.Cylinder_3.material}
                position={[-14.97, 2.13, -7.21]}
              />
              <mesh
                geometry={nodes.Cylinder_2_2.geometry}
                material={nodes.Cylinder_2_2.material}
                position={[-14.97, -4.79, -7.21]}
              />
              <mesh
                geometry={nodes.Cylinder_1_3.geometry}
                material={nodes.Cylinder_1_3.material}
                position={[-14.97, -4.79, -15.85]}
              />
              <mesh
                geometry={nodes.Cylinder_3_2.geometry}
                material={nodes.Cylinder_3_2.material}
                position={[-14.97, 18, -15.85]}
              />
              <mesh
                geometry={nodes.Sweep.geometry}
                material={nodes.Sweep.material}
                position={[58.8, -79.05, 14.7]}
              >
                <mesh
                  geometry={nodes.Cap_1.geometry}
                  material={nodes.Cap_1.material}
                  position={[-73.88, 98.75, -30.58]}
                  rotation={[-Math.PI / 2, 0, 1.08]}
                />
                <mesh
                  geometry={nodes.Cap_2.geometry}
                  material={nodes.Cap_2.material}
                  position={[-98.03, 86.15, -8.57]}
                  rotation={[0, 1.57, -2]}
                />
              </mesh>
              <mesh
                geometry={nodes.sink.geometry}
                material={nodes.sink.material}
                position={[-20.65, 38.85, 14.05]}
              />
              <mesh
                geometry={nodes.Door.geometry}
                material={nodes.Door.material}
                position={[6.96, -4.56, -37.43]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 3.76, 42.54]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_3.geometry}
                    material={nodes.Cylinder_2_3.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_4.geometry}
                    material={nodes.Cylinder_1_4.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_4_2.geometry}
                    material={nodes.Cylinder_4_2.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_4.geometry}
                material={nodes.Door_4.material}
                position={[7.12, -4.56, 62.53]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 3.6, -42.59]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_4.geometry}
                    material={nodes.Cylinder_2_4.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_5.geometry}
                    material={nodes.Cylinder_1_5.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_5_2.geometry}
                    material={nodes.Cylinder_5_2.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_7.geometry}
                material={nodes.Door_7.material}
                position={[9.49, -4.56, 71.31]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 1.23, 2.63]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_5.geometry}
                    material={nodes.Cylinder_2_5.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_6.geometry}
                    material={nodes.Cylinder_1_6.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_6_1.geometry}
                    material={nodes.Cylinder_6_1.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_6.geometry}
                material={nodes.Door_6.material}
                position={[9.49, 12.96, 71.31]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_6.geometry}
                    material={nodes.Cylinder_2_6.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_7.geometry}
                    material={nodes.Cylinder_1_7.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_7.geometry}
                    material={nodes.Cylinder_7.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_5.geometry}
                material={nodes.Door_5.material}
                position={[9.49, 12.96, 17.28]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_7.geometry}
                    material={nodes.Cylinder_2_7.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_8.geometry}
                    material={nodes.Cylinder_1_8.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_8.geometry}
                    material={nodes.Cylinder_8.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_3.geometry}
                material={nodes.Door_3.material}
                position={[9.49, -4.56, -89.73]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 1.23, 43.15]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_8.geometry}
                    material={nodes.Cylinder_2_8.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_9.geometry}
                    material={nodes.Cylinder_1_9.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_9.geometry}
                    material={nodes.Cylinder_9.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_2.geometry}
                material={nodes.Door_2.material}
                position={[9.49, 12.96, -89.73]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_9.geometry}
                    material={nodes.Cylinder_2_9.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_10.geometry}
                    material={nodes.Cylinder_1_10.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_10.geometry}
                    material={nodes.Cylinder_10.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_1.geometry}
                material={nodes.Door_1.material}
                position={[9.49, 12.96, -38.07]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_10.geometry}
                    material={nodes.Cylinder_2_10.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_11.geometry}
                    material={nodes.Cylinder_1_11.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_11.geometry}
                    material={nodes.Cylinder_11.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Cabs.geometry}
                material={nodes.Cabs.material}
                position={[-22.27, 2.37, 14.7]}
              />
            </group>
            <group position={[110.48, -126.19, 61.55]} rotation={[0, 1.57, 0]}>
              <group position={[58.8, -79.05, 14.7]}>
                <mesh
                  geometry={nodes.counters_2.geometry}
                  material={nodes.counters_2.material}
                  position={[-73.1, 133.69, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Bowl_Cylinder_2.geometry}
                material={nodes.Bowl_Cylinder_2.material}
                position={[-25.28, 57.01, -65.08]}
              />
              <mesh
                geometry={nodes.Cylinder_5_3.geometry}
                material={nodes.Cylinder_5_3.material}
                position={[-23.26, 7.16, 6.24]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Cylinder_4_3.geometry}
                material={nodes.Cylinder_4_3.material}
                position={[-14.97, 7.16, -0.3]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Cylinder_3_3.geometry}
                material={nodes.Cylinder_3_3.material}
                position={[-14.97, 2.13, -7.21]}
              />
              <mesh
                geometry={nodes.Cylinder_2_11.geometry}
                material={nodes.Cylinder_2_11.material}
                position={[-14.97, -4.79, -7.21]}
              />
              <mesh
                geometry={nodes.Cylinder_1_12.geometry}
                material={nodes.Cylinder_1_12.material}
                position={[-14.97, -4.79, -15.85]}
              />
              <mesh
                geometry={nodes.Cylinder_12.geometry}
                material={nodes.Cylinder_12.material}
                position={[-14.97, 18, -15.85]}
              />
              <mesh
                geometry={nodes.Sweep_2.geometry}
                material={nodes.Sweep_2.material}
                position={[58.8, -79.05, 14.7]}
              >
                <mesh
                  geometry={nodes.Cap_1_2.geometry}
                  material={nodes.Cap_1_2.material}
                  position={[-73.88, 98.75, -30.58]}
                  rotation={[-Math.PI / 2, 0, 1.08]}
                />
                <mesh
                  geometry={nodes.Cap_2_2.geometry}
                  material={nodes.Cap_2_2.material}
                  position={[-98.03, 86.15, -8.57]}
                  rotation={[0, 1.57, -2]}
                />
              </mesh>
              <mesh
                geometry={nodes.Door_2_2.geometry}
                material={nodes.Door_2_2.material}
                position={[6.96, -4.56, -37.43]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 3.76, 42.54]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_12.geometry}
                    material={nodes.Cylinder_2_12.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_13.geometry}
                    material={nodes.Cylinder_1_13.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_13.geometry}
                    material={nodes.Cylinder_13.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_4_2.geometry}
                material={nodes.Door_4_2.material}
                position={[7.12, -4.56, 62.53]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 3.6, -42.59]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_13.geometry}
                    material={nodes.Cylinder_2_13.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_14.geometry}
                    material={nodes.Cylinder_1_14.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_14.geometry}
                    material={nodes.Cylinder_14.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_7_2.geometry}
                material={nodes.Door_7_2.material}
                position={[9.49, -4.56, 71.31]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 1.23, 2.63]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_14.geometry}
                    material={nodes.Cylinder_2_14.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_15.geometry}
                    material={nodes.Cylinder_1_15.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_15.geometry}
                    material={nodes.Cylinder_15.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_6_2.geometry}
                material={nodes.Door_6_2.material}
                position={[9.49, 12.96, 71.31]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_15.geometry}
                    material={nodes.Cylinder_2_15.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_16.geometry}
                    material={nodes.Cylinder_1_16.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_16.geometry}
                    material={nodes.Cylinder_16.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_5_2.geometry}
                material={nodes.Door_5_2.material}
                position={[9.49, 12.96, 17.28]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_16.geometry}
                    material={nodes.Cylinder_2_16.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_17.geometry}
                    material={nodes.Cylinder_1_17.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_17.geometry}
                    material={nodes.Cylinder_17.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_3_2.geometry}
                material={nodes.Door_3_2.material}
                position={[9.49, -4.56, -89.73]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-26.13, 1.23, 43.15]}
                  rotation={[0, 0, Math.PI / 2]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_17.geometry}
                    material={nodes.Cylinder_2_17.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_18.geometry}
                    material={nodes.Cylinder_1_18.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_18.geometry}
                    material={nodes.Cylinder_18.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_2_3.geometry}
                material={nodes.Door_2_3.material}
                position={[9.49, 12.96, -89.73]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_18.geometry}
                    material={nodes.Cylinder_2_18.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_19.geometry}
                    material={nodes.Cylinder_1_19.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_19.geometry}
                    material={nodes.Cylinder_19.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Door_1_2.geometry}
                material={nodes.Door_1_2.material}
                position={[9.49, 12.96, -38.07]}
                rotation={[0, 0, -Math.PI / 2]}
              >
                <group
                  position={[-30.1, 1.23, 23.2]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                >
                  <mesh
                    geometry={nodes.Cylinder_2_19.geometry}
                    material={nodes.Cylinder_2_19.material}
                    position={[-0.83, -4.47, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_1_20.geometry}
                    material={nodes.Cylinder_1_20.material}
                    position={[-0.83, 4.23, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                  />
                  <mesh
                    geometry={nodes.Cylinder_20.geometry}
                    material={nodes.Cylinder_20.material}
                    position={[1.66, 0.24, 0]}
                  />
                </group>
              </mesh>
              <mesh
                geometry={nodes.Cabs_2.geometry}
                material={nodes.Cabs_2.material}
                position={[-22.27, 2.37, 14.7]}
              />
            </group>
            <group position={[229.93, -117.14, -188.68]} rotation={[0, 0.7, 0]}>
              <group
                position={[-7.82, -10.7, 0.14]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.cover.geometry}
                  material={nodes.cover.material}
                  position={[-0.26, 0, -43.97]}
                  scale={0.01}
                />
                <mesh
                  geometry={nodes.base.geometry}
                  material={nodes.base.material}
                  position={[41.34, -0.1, 27.74]}
                  scale={[0.01, 0.01, 0.01]}
                />
              </group>
              <group
                position={[-65.36, 2.67, 3.54]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
              >
                <mesh
                  geometry={nodes.wood.geometry}
                  material={nodes.wood.material}
                  position={[18.32, 13.77, -6.24]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.01, -0.01, 0.01]}
                />
                <mesh
                  geometry={nodes.seat.geometry}
                  material={nodes.seat.material}
                  position={[17.44, 0, -8.86]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={0.01}
                />
              </group>
              <group
                position={[9.52, 2.67, 62.04]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.wood_2.geometry}
                  material={nodes.wood_2.material}
                  position={[18.32, 13.77, -6.24]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.01, -0.01, 0.01]}
                />
                <mesh
                  geometry={nodes.seat_2.geometry}
                  material={nodes.seat_2.material}
                  position={[17.44, 0, -8.86]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={0.01}
                />
              </group>
              <group
                position={[9.52, 2.67, -67.24]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              >
                <mesh
                  geometry={nodes.wood_3.geometry}
                  material={nodes.wood_3.material}
                  position={[18.32, 13.77, -6.24]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.01, -0.01, 0.01]}
                />
                <mesh
                  geometry={nodes.seat_3.geometry}
                  material={nodes.seat_3.material}
                  position={[17.44, 0, -8.86]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={0.01}
                />
              </group>
              <group
                position={[54.14, 2.67, 1.51]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.wood_4.geometry}
                  material={nodes.wood_4.material}
                  position={[18.32, 13.77, -6.24]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.01, -0.01, 0.01]}
                />
                <mesh
                  geometry={nodes.seat_4.geometry}
                  material={nodes.seat_4.material}
                  position={[17.44, 0, -8.86]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={0.01}
                />
              </group>
            </group>
          </group>
          <group position={[-566.92, 262.15, 24.34]}>
            <group
              position={[189.08, -135.24, -12.6]}
              rotation={[-Math.PI / 2, 0, -1.48]}
            >
              <mesh
                geometry={nodes.vase.geometry}
                material={nodes.vase.material}
                position={[4.11, 0.37, -18.41]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.branches.geometry}
                material={nodes.branches.material}
                position={[2.76, -0.56, 43.99]}
                rotation={[1.61, 1.48, 0.04]}
                scale={[0.01, 0.01, 0.01]}
              />
            </group>
            <group
              position={[-190.82, -105.72, -371.95]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.vase_2.geometry}
                material={nodes.vase_2.material}
                position={[-0.89, -0.41, -13.01]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.brances.geometry}
                material={nodes.brances.material}
                position={[-1.3, -0.59, 13.45]}
                rotation={[1.57, 0.18, 0.07]}
                scale={[0.01, 0.01, 0.01]}
              />
            </group>
            <group
              position={[-191.56, -170.54, -371.83]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.cover_2.geometry}
                material={nodes.cover_2.material}
                position={[-0.11, 0, -43.97]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_2.geometry}
                material={nodes.base_2.material}
                position={[17.47, -0.04, 27.74]}
                scale={[0.01, 0.01, 0.01]}
              />
            </group>
            <group
              position={[-190.81, -135.24, -12.6]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.vase_3.geometry}
                material={nodes.vase_3.material}
                position={[4.11, 0.37, -18.41]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.branches_2.geometry}
                material={nodes.branches_2.material}
                position={[2.76, -0.56, 43.99]}
                rotation={[1.61, 1.48, 0.04]}
                scale={[0.01, 0.01, 0.01]}
              />
            </group>
            <group
              position={[3.46, -160.93, -13.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.handles.geometry}
                material={nodes.handles.material}
                position={[-85.33, 18.23, 7.81]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0, 0.01, 0]}
              />
              <mesh
                geometry={nodes.doors.geometry}
                material={nodes.doors.material}
                position={[0, -1.68, -15]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_3.geometry}
                material={nodes.base_3.material}
                position={[0, -1.68, -15]}
                scale={0.01}
              />
            </group>
            <group
              position={[3.46, -191.28, -13.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.handles_2.geometry}
                material={nodes.handles_2.material}
                position={[-85.33, 18.23, 7.81]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0, 0.01, 0]}
              />
              <mesh
                geometry={nodes.doors_2.geometry}
                material={nodes.doors_2.material}
                position={[0, -1.68, -15]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_4.geometry}
                material={nodes.base_4.material}
                position={[0, -1.68, -15]}
                scale={0.01}
              />
            </group>
            <group
              position={[43.16, -173.24, -377.7]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.seat_5.geometry}
                material={nodes.seat_5.material}
                position={[-70.08, 13.99, -14.24]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.back.geometry}
                material={nodes.back.material}
                position={[-70.08, -46.12, -6.74]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.left.geometry}
                material={nodes.left.material}
                position={[-110.55, -13.72, -6.74]}
                rotation={[Math.PI / 2, -1.57, 0]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.base_5.geometry}
                material={nodes.base_5.material}
                position={[4.63, 13.99, -33.39]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.legs.geometry}
                material={nodes.legs.material}
                position={[-120.08, 0.99, -33.29]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.back_2.geometry}
                material={nodes.back_2.material}
                position={[4.63, -46.12, -6.74]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.back_3.geometry}
                material={nodes.back_3.material}
                position={[78.76, -46.12, -6.74]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.right.geometry}
                material={nodes.right.material}
                position={[110.55, -13.72, -6.74]}
                rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.seat_6.geometry}
                material={nodes.seat_6.material}
                position={[4.63, 13.99, -14.24]}
                scale={[0.01, -0.01, 0.01]}
              />
              <mesh
                geometry={nodes.seat_7.geometry}
                material={nodes.seat_7.material}
                position={[78.85, 13.99, -14.24]}
                scale={[0.01, -0.01, 0.01]}
              />
            </group>
            <group
              position={[-227.97, 256.73, -103.91]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.towel_dryer.geometry}
                material={nodes.towel_dryer.material}
                position={[-1.95, 0, 6.94]}
              />
              <mesh
                geometry={nodes.towel.geometry}
                material={nodes.towel.material}
                position={[4.09, 10.54, -9.21]}
              />
            </group>
            <group
              position={[181.75, -173.93, -91.18]}
              rotation={[-Math.PI / 2, 0, -0.62]}
            >
              <mesh
                geometry={nodes.metal.geometry}
                material={nodes.metal.material}
                position={[-35.58, -36.84, -32.51]}
                rotation={[0, 0, -Math.PI]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_6.geometry}
                material={nodes.base_6.material}
                position={[0, 0, -22.84]}
                rotation={[0, 0, -Math.PI]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.seat_8.geometry}
                material={nodes.seat_8.material}
                position={[-3.69, -0.12, -14.29]}
                rotation={[0, 0, -Math.PI]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.back_4.geometry}
                material={nodes.back_4.material}
                position={[23.81, 26.46, 18.69]}
                rotation={[-Math.PI / 2, 0, -2.78]}
                scale={[0.01, 0.01, 0.01]}
              />
            </group>
            <group
              position={[-121.67, 146.09, 351.97]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                geometry={nodes.blanket.geometry}
                material={nodes.blanket.material}
                position={[54.35, 1.19, -27.95]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_7.geometry}
                material={nodes.base_7.material}
                position={[91.91, 105.98, -26.97]}
                rotation={[Math.PI / 2, 1.57, 0]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.pillow.geometry}
                material={nodes.pillow.material}
                position={[-311.9, -110.88, -100.18]}
                rotation={[2.09, 0, -Math.PI]}
                scale={0.11}
              />
              <mesh
                geometry={nodes.pillow_2.geometry}
                material={nodes.pillow_2.material}
                position={[-231.63, -110.88, -100.18]}
                rotation={[2.09, 0, -Math.PI]}
                scale={0.11}
              />
            </group>
            <group
              position={[-91.37, 135.96, -379.13]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.base_8.geometry}
                material={nodes.base_8.material}
                position={[38.27, 74.33, 32.28]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.cover_3.geometry}
                material={nodes.cover_3.material}
                position={[0, 0, 35.16]}
                scale={0.01}
              />
            </group>
            <group
              position={[-86.62, 158.94, -81.22]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.soap.geometry}
                material={nodes.soap.material}
                position={[-20.45, 40.88, 45.21]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.dish.geometry}
                material={nodes.dish.material}
                position={[-20.45, 40.88, 44.29]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_9.geometry}
                material={nodes.base_9.material}
                position={[1.15, 0.39, -1.06]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.03}
              />
              <mesh
                geometry={nodes.doors_3.geometry}
                material={nodes.doors_3.material}
                position={[1.15, 0.39, -1.06]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.03}
              />
              <mesh
                geometry={nodes.toothbrush_1.geometry}
                material={nodes.toothbrush_1.material}
                position={[-16.94, -42.14, 55.42]}
                rotation={[1.81, 0.29, -0.04]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.stand.geometry}
                material={nodes.stand.material}
                position={[-17.53, -39.74, 44.47]}
                rotation={[0, 0, 1.75]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.brushes.geometry}
                material={nodes.brushes.material}
                position={[-20.37, -38.83, 54.95]}
                rotation={[-Math.PI / 2, 0.64, 2.79]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.hot.geometry}
                material={nodes.hot.material}
                position={[0.06, 0.56, -1.31]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.03}
              />
              <mesh
                geometry={nodes.toothbrush_2.geometry}
                material={nodes.toothbrush_2.material}
                position={[-20.37, -38.83, 54.95]}
                rotation={[-Math.PI / 2, 0.64, 2.79]}
                scale={[0.01, 0.01, 0.01]}
              />
              <mesh
                geometry={nodes.faucets.geometry}
                material={nodes.faucets.material}
                position={[1.71, 17.5, -1.31]}
                rotation={[0, 0, 1.4]}
                scale={[0.03, 0.03, 0.03]}
              />
              <mesh
                geometry={nodes.sink_2.geometry}
                material={nodes.sink_2.material}
                position={[2.32, 0.54, 36.21]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.03}
              />
              <mesh
                geometry={nodes.handles_3.geometry}
                material={nodes.handles_3.material}
                position={[27, 7.41, 16.18]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.03}
              />
              <mesh
                geometry={nodes.cold.geometry}
                material={nodes.cold.material}
                position={[0.06, 21.45, -1.31]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.03}
              />
            </group>
            <group
              position={[-56.48, 144.66, -69.3]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.base_10.geometry}
                material={nodes.base_10.material}
                position={[-0.05, -171.87, 0.04]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.button.geometry}
                material={nodes.button.material}
                position={[-0.05, 0, 0.04]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
            </group>
            <group
              position={[-176.78, 196.27, 73.88]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.glass.geometry}
                material={nodes.glass.material}
                position={[13.76, -14.29, -94.57]}
                scale={[0.01, 0.01, 0.03]}
              />
              <mesh
                geometry={nodes.skirting.geometry}
                material={nodes.skirting.material}
                position={[12.63, -12.4, -95.15]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.metal_2.geometry}
                material={nodes.metal_2.material}
                position={[42.3, 41.58, -87.96]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.shell.geometry}
                material={nodes.shell.material}
                position={[35.29, -20.6, -95.37]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.base_11.geometry}
                material={nodes.base_11.material}
                position={[0.2, -0.02, -99.34]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.stand_2.geometry}
                material={nodes.stand_2.material}
                position={[4.7, 38.72, 31.66]}
                rotation={[0, 0, Math.PI / 2]}
                scale={0.01}
              />
              <mesh
                geometry={nodes.habdles.geometry}
                material={nodes.habdles.material}
                position={[40.57, -15.11, 6.43]}
                rotation={[0, 0, 1.92]}
                scale={0.01}
              />
            </group>
            <group
              position={[-99.06, 151.39, -308.78]}
              rotation={[-Math.PI / 2, 0, 1.93]}
            >
              <mesh
                geometry={nodes.wheels.geometry}
                material={nodes.wheels.material}
                position={[-24.29, 0.61, -50.68]}
                rotation={[Math.PI / 2, -1.04, 0]}
                scale={[0.02, 0.02, 0.02]}
              />
              <mesh
                geometry={nodes.seat_9.geometry}
                material={nodes.seat_9.material}
                position={[4.87, -1.26, -6.3]}
                rotation={[0, 0, -1.57]}
                scale={[0.02, 0.02, 0.02]}
              />
              <mesh
                geometry={nodes.plastic.geometry}
                material={nodes.plastic.material}
                position={[-23.2, -10.52, 41.64]}
                rotation={[0.08, -1.51, -1.49]}
                scale={[0.02, 0.02, 0.02]}
              />
            </group>
            <mesh
              geometry={nodes.TV_1.geometry}
              material={nodes.TV_1.material}
              position={[-4.53, -68.06, 3.03]}
              rotation={[Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.TV.geometry}
              material={nodes.TV.material}
              position={[-140.59, 246.97, 137.27]}
            />
            <mesh
              geometry={nodes.coffee_table_2.geometry}
              material={nodes.coffee_table_2.material}
              position={[19.63, -185.99, -239.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={0.03}
            />
            <mesh
              geometry={nodes.Door_Instance_2.geometry}
              material={nodes.Door_Instance_2.material}
              position={[62.41, 197.71, 7.62]}
            />
            <mesh
              geometry={nodes.Door_Instance_3.geometry}
              material={nodes.Door_Instance_3.material}
              position={[62.41, 197.71, 242.67]}
            />
            <mesh
              geometry={nodes.Door_Instance_1.geometry}
              material={nodes.Door_Instance_1.material}
              position={[62.41, 197.71, -218.7]}
            />
            <mesh
              geometry={nodes.Door_Instance.geometry}
              material={nodes.Door_Instance.material}
              position={[269.04, -104.48, -214.05]}
            />
            <mesh
              geometry={nodes.Door_3_3.geometry}
              material={nodes.Door_3_3.material}
              position={[61.74, -106.81, 301.31]}
            />
          </group>
          <group position={[-680.95, 109.22, 462.29]}>
            <mesh
              geometry={nodes["Window_01-House_Main"].geometry}
              material={nodes["Window_01-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_01-window"].geometry}
              material={nodes["Window_01-window"].material}
            />
          </group>
          <group position={[-88.44, 183.22, 462.33]}>
            <mesh
              geometry={nodes["Window_02-House_Main"].geometry}
              material={nodes["Window_02-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_02-window"].geometry}
              material={nodes["Window_02-window"].material}
            />
          </group>
          <group position={[104.06, 183.22, 462.33]}>
            <mesh
              geometry={nodes["Window_03-House_Main"].geometry}
              material={nodes["Window_03-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_03-window"].geometry}
              material={nodes["Window_03-window"].material}
            />
          </group>
          <group
            position={[-512, 109.22, -404.24]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Window_06-House_Main"].geometry}
              material={nodes["Window_06-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_06-window"].geometry}
              material={nodes["Window_06-window"].material}
            />
            <mesh
              geometry={nodes["Window_06-window_1"].geometry}
              material={nodes["Window_06-window_1"].material}
            />
          </group>
          <group
            position={[-30, 109.22, -656.3]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Window_07-House_Main"].geometry}
              material={nodes["Window_07-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_07-window"].geometry}
              material={nodes["Window_07-window"].material}
            />
            <mesh
              geometry={nodes["Window_07-window_1"].geometry}
              material={nodes["Window_07-window_1"].material}
            />
          </group>
          <group position={[-342.94, 403.32, 499.29]}>
            <mesh
              geometry={nodes["Window_09-House_Main"].geometry}
              material={nodes["Window_09-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_09-window"].geometry}
              material={nodes["Window_09-window"].material}
            />
            <mesh
              geometry={nodes["Window_09-window_1"].geometry}
              material={nodes["Window_09-window_1"].material}
            />
          </group>
          <group position={[7.38, 403.32, 489.78]}>
            <mesh
              geometry={nodes["Window_10-House_Main"].geometry}
              material={nodes["Window_10-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_10-window"].geometry}
              material={nodes["Window_10-window"].material}
            />
          </group>
          <group position={[-680.95, 403.32, 492.78]}>
            <mesh
              geometry={nodes["Window_11-House_Main"].geometry}
              material={nodes["Window_11-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_11-window"].geometry}
              material={nodes["Window_11-window"].material}
            />
          </group>
          <group
            position={[-786.5, 403.32, -404.2]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Window_12-House_Main"].geometry}
              material={nodes["Window_12-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_12-window"].geometry}
              material={nodes["Window_12-window"].material}
            />
            <mesh
              geometry={nodes["Window_12-window_1"].geometry}
              material={nodes["Window_12-window_1"].material}
            />
          </group>
          <group
            position={[-437.5, 403.32, -404.2]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Window_13-House_Main"].geometry}
              material={nodes["Window_13-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_13-window"].geometry}
              material={nodes["Window_13-window"].material}
            />
            <mesh
              geometry={nodes["Window_13-window_1"].geometry}
              material={nodes["Window_13-window_1"].material}
            />
          </group>
          <group
            position={[-123, 455.3, -404.15]}
            rotation={[Math.PI, 0, -Math.PI]}
          >
            <mesh
              geometry={nodes["Window_14-House_Main"].geometry}
              material={nodes["Window_14-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_14-window"].geometry}
              material={nodes["Window_14-window"].material}
            />
            <mesh
              geometry={nodes["Window_14-window_1"].geometry}
              material={nodes["Window_14-window_1"].material}
            />
          </group>
          <group
            position={[79, 455.3, -404.15]}
            rotation={[Math.PI, 0, -Math.PI]}
          >
            <mesh
              geometry={nodes["Window_15-House_Main"].geometry}
              material={nodes["Window_15-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_15-window"].geometry}
              material={nodes["Window_15-window"].material}
            />
            <mesh
              geometry={nodes["Window_15-window_1"].geometry}
              material={nodes["Window_15-window_1"].material}
            />
          </group>
          <group position={[221.91, 113.1, -523.03]} rotation={[0, 1.57, 0]}>
            <mesh
              geometry={nodes["Window_01_1-House_Main"].geometry}
              material={nodes["Window_01_1-House_Main"].material}
            />
            <mesh
              geometry={nodes["Window_01_1-window"].geometry}
              material={nodes["Window_01_1-window"].material}
            />
          </group>
          <group position={[-214, 266, 473.35]}>
            <mesh
              geometry={nodes["Wall_Light_008-Lights"].geometry}
              material={nodes["Wall_Light_008-Lights"].material}
            />
            <mesh
              geometry={nodes["Wall_Light_008-House_Main"].geometry}
              material={nodes["Wall_Light_008-House_Main"].material}
            />
          </group>
          <group position={[-473.5, 266, 473.35]}>
            <mesh
              geometry={nodes["Wall_Light_008_2-Lights"].geometry}
              material={nodes["Wall_Light_008_2-Lights"].material}
            />
            <mesh
              geometry={nodes["Wall_Light_008_2-House_Main"].geometry}
              material={nodes["Wall_Light_008_2-House_Main"].material}
            />
          </group>
          <group
            position={[-338.5, 266, -415.4]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Wall_Light_008_5-Lights"].geometry}
              material={nodes["Wall_Light_008_5-Lights"].material}
            />
            <mesh
              geometry={nodes["Wall_Light_008_5-House_Main"].geometry}
              material={nodes["Wall_Light_008_5-House_Main"].material}
            />
          </group>
          <group
            position={[-266, 266, -667.75]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              geometry={nodes["Wall_Light_008_6-Lights"].geometry}
              material={nodes["Wall_Light_008_6-Lights"].material}
            />
            <mesh
              geometry={nodes["Wall_Light_008_6-House_Main"].geometry}
              material={nodes["Wall_Light_008_6-House_Main"].material}
            />
          </group>
          <mesh
            geometry={nodes["Floor_2-House_Main"].geometry}
            material={nodes["Floor_2-House_Main"].material}
          />
          <mesh
            geometry={nodes["Floor_2-Siding"].geometry}
            material={nodes["Floor_2-Siding"].material}
          />
          <group position={[8.15, 0, 0]}>
            <mesh
              geometry={nodes.Stud.geometry}
              material={nodes.Stud.material}
            />
            <mesh
              geometry={nodes.Stud_2.geometry}
              material={nodes.Stud_2.material}
              position={[0, 13.32, 0]}
            />
            <mesh
              geometry={nodes.Stud_4.geometry}
              material={nodes.Stud_4.material}
              position={[-881.52, 663.62, -226.61]}
              rotation={[Math.PI / 2, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Stud_1.geometry}
              material={nodes.Stud_1.material}
              position={[-881.52, 663.62, 315.09]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Stud_3.geometry}
              material={nodes.Stud_3.material}
              position={[-881.52, 813.58, -3.41]}
            />
            <mesh
              geometry={nodes.Stud_5.geometry}
              material={nodes.Stud_5.material}
              position={[-881.52, 837.53, 45.69]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <group position={[121.92, 0, 0]}>
              <mesh
                geometry={nodes.Stud_2_2.geometry}
                material={nodes.Stud_2_2.material}
              />
              <mesh
                geometry={nodes.Stud_2_3.geometry}
                material={nodes.Stud_2_3.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_2.geometry}
                material={nodes.Stud_4_2.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_2.geometry}
                material={nodes.Stud_1_2.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_2.geometry}
                material={nodes.Stud_3_2.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_2.geometry}
                material={nodes.Stud_5_2.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[243.84, 0, 0]}>
              <mesh
                geometry={nodes.Stud_3_3.geometry}
                material={nodes.Stud_3_3.material}
              />
              <mesh
                geometry={nodes.Stud_2_4.geometry}
                material={nodes.Stud_2_4.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_3.geometry}
                material={nodes.Stud_4_3.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_3.geometry}
                material={nodes.Stud_1_3.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_4.geometry}
                material={nodes.Stud_3_4.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_3.geometry}
                material={nodes.Stud_5_3.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[365.76, 0, 0]}>
              <mesh
                geometry={nodes.Stud_4_4.geometry}
                material={nodes.Stud_4_4.material}
              />
              <mesh
                geometry={nodes.Stud_2_5.geometry}
                material={nodes.Stud_2_5.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_5.geometry}
                material={nodes.Stud_4_5.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_4.geometry}
                material={nodes.Stud_1_4.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_5.geometry}
                material={nodes.Stud_3_5.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_4.geometry}
                material={nodes.Stud_5_4.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[487.68, 0, 0]}>
              <mesh
                geometry={nodes.Stud_5_5.geometry}
                material={nodes.Stud_5_5.material}
              />
              <mesh
                geometry={nodes.Stud_2_6.geometry}
                material={nodes.Stud_2_6.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_6.geometry}
                material={nodes.Stud_4_6.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_5.geometry}
                material={nodes.Stud_1_5.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_6.geometry}
                material={nodes.Stud_3_6.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_6.geometry}
                material={nodes.Stud_5_6.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[609.6, 0, 0]}>
              <mesh
                geometry={nodes.Stud_6.geometry}
                material={nodes.Stud_6.material}
              />
              <mesh
                geometry={nodes.Stud_2_7.geometry}
                material={nodes.Stud_2_7.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_7.geometry}
                material={nodes.Stud_4_7.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_6.geometry}
                material={nodes.Stud_1_6.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_7.geometry}
                material={nodes.Stud_3_7.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_7.geometry}
                material={nodes.Stud_5_7.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[731.52, 0, 0]}>
              <mesh
                geometry={nodes.Stud_7.geometry}
                material={nodes.Stud_7.material}
              />
              <mesh
                geometry={nodes.Stud_2_8.geometry}
                material={nodes.Stud_2_8.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_8.geometry}
                material={nodes.Stud_4_8.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_7.geometry}
                material={nodes.Stud_1_7.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_8.geometry}
                material={nodes.Stud_3_8.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_8.geometry}
                material={nodes.Stud_5_8.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[853.44, 0, 0]}>
              <mesh
                geometry={nodes.Stud_8.geometry}
                material={nodes.Stud_8.material}
              />
              <mesh
                geometry={nodes.Stud_2_9.geometry}
                material={nodes.Stud_2_9.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_9.geometry}
                material={nodes.Stud_4_9.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_8.geometry}
                material={nodes.Stud_1_8.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_9.geometry}
                material={nodes.Stud_3_9.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_9.geometry}
                material={nodes.Stud_5_9.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[975.36, 0, 0]}>
              <mesh
                geometry={nodes.Stud_9.geometry}
                material={nodes.Stud_9.material}
              />
              <mesh
                geometry={nodes.Stud_2_10.geometry}
                material={nodes.Stud_2_10.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_10.geometry}
                material={nodes.Stud_4_10.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_9.geometry}
                material={nodes.Stud_1_9.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_10.geometry}
                material={nodes.Stud_3_10.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_10.geometry}
                material={nodes.Stud_5_10.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group position={[1097.28, 0, 0]}>
              <mesh
                geometry={nodes.Stud_10.geometry}
                material={nodes.Stud_10.material}
              />
              <mesh
                geometry={nodes.Stud_2_11.geometry}
                material={nodes.Stud_2_11.material}
                position={[0, 13.32, 0]}
              />
              <mesh
                geometry={nodes.Stud_4_11.geometry}
                material={nodes.Stud_4_11.material}
                position={[-881.52, 663.62, -226.61]}
                rotation={[Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Stud_1_10.geometry}
                material={nodes.Stud_1_10.material}
                position={[-881.52, 663.62, 315.09]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Stud_3_11.geometry}
                material={nodes.Stud_3_11.material}
                position={[-881.52, 813.58, -3.41]}
              />
              <mesh
                geometry={nodes.Stud_5_11.geometry}
                material={nodes.Stud_5_11.material}
                position={[-881.52, 837.53, 45.69]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
          </group>
          <mesh
            geometry={nodes.Wall.geometry}
            material={nodes.Wall.material}
            position={[-483.71, 314.69, 29.04]}
          />
          <mesh
            geometry={nodes.Floor_1.geometry}
            material={nodes.Floor_1.material}
          />
          <mesh
            geometry={nodes.Floor_1_1.geometry}
            material={nodes.Floor_1_1.material}
          />
          <mesh
            geometry={nodes.Attic_Level.geometry}
            material={nodes.Attic_Level.material}
            position={[20.43, 600.89, 46.95]}
          />
          <mesh
            geometry={nodes.Floor_2_1.geometry}
            material={nodes.Floor_2_1.material}
          />
          <mesh
            geometry={nodes.Concrete.geometry}
            material={nodes.Concrete.material}
          />
          <mesh
            geometry={nodes.Door_Front.geometry}
            material={nodes.Door_Front.material}
            position={[-343.9, 61.38, 457.8]}
          />
          <mesh
            geometry={nodes.Stone_Wall.geometry}
            material={nodes.Stone_Wall.material}
          />
          <mesh
            geometry={nodes.Door_Back.geometry}
            material={nodes.Door_Back.material}
            position={[-285.99, 61.38, -535.5]}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes.Attic_Level_1.geometry}
            material={nodes.Attic_Level_1.material}
            position={[20.43, 352.62, 46.95]}
          />
          <mesh
            geometry={nodes.Attic_Level_2.geometry}
            material={nodes.Attic_Level_2.material}
            position={[20.43, 48.04, 46.95]}
          />
        </group>
        <mesh
          geometry={nodes.Attic_Heat.geometry}
          material={materials.Mat}
          position={[-906.94, 594.63, -196.26]}
          rotation={[0, 0, Math.PI / 2]}
        />
      </group>
      <mesh geometry={nodes.Ground.geometry} material={materials.ground} />
    </group>
  );
}

useGLTF.preload("/House.gltf");
