/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { currentNum } = props;
  const { nodes, materials } = useGLTF("/yoo4.gltf");
  return (
    <group ref={group} scale={0.01} {...props} dispose={null}>
      <group position={[0, 56.57, 0]}>
        <group position={[0, 56.57, 0]}>
          {currentNum === 1 && (
            <mesh
              geometry={nodes.stack1.geometry}
              material={nodes.stack1.material}
              position={[0, -53.6, 0]}
            />
          )}
          {currentNum === 2 && (
            <mesh
              geometry={nodes.stack2.geometry}
              material={nodes.stack2.material}
            />
          )}
          {currentNum === 3 && (
            <mesh
              geometry={nodes.stack3.geometry}
              material={nodes.stack3.material}
            />
          )}
        </group>
        <mesh
          geometry={nodes.cube1.geometry}
          material={nodes.cube1.material}
          position={[0, -56.57, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/yoo4.gltf");
